services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=calendar
      - POSTGRES_DB=calendar
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 30

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=calendar
      - POSTGRES_DB=calendar
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CORS_ORIGIN=*
      - PUBLIC_ORIGIN=http://localhost
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:8080"

volumes:
  db_data: {}


